### ISSUE TITLE
Louis Turbo EM

### ISSUE THREAD

**Issue by YuyingHUANG** [Gaochenyin/Monte-Carlo-Expectation-Maximization#3]
# Louis Turbo EM
Since the posterior distribution is hard to be estimated, we can apply some acceleration methods to better estimate them, Therefore, it helps to calibrate the estimating process and save time.

**Comment by Gaochenyin** [comment]
![ltem_beta1](https://user-images.githubusercontent.com/39727759/48658666-a7661a00-ea80-11e8-9cd4-444301d4e941.png)
![ltem_beta2](https://user-images.githubusercontent.com/39727759/48658667-a7661a00-ea80-11e8-9e83-ae22281cf3a4.png)
![ltem_pi1](https://user-images.githubusercontent.com/39727759/48658668-a7661a00-ea80-11e8-9db2-c31f6dc6a942.png)
![ltem_sigma1](https://user-images.githubusercontent.com/39727759/48658669-a7661a00-ea80-11e8-9407-6388b74e8ac1.png)
![ltem_sigma2](https://user-images.githubusercontent.com/39727759/48658670-a7feb080-ea80-11e8-9ed6-da9ff06d44c1.png)

**Comment by Gaochenyin** [comment]
Complete Convergence iteration
